apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-management

resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: keycloak-realm-config
    files:
      - realm-export.json

generatorOptions:
  disableNameSuffixHash: true
