apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: task-management
spec:
  selector:
    app: keycloak
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP