apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: task-management
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      name: http
  type: ClusterIP

