apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-management

resources:
  - backend
  - frontend
  - nginx
  - database
  - keycloak
  - configmap.yaml
  - secrets.yaml
  - ingress.yaml
