apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: task-management
type: Opaque
stringData:
  DB_PASSWORD: "taskpassword123"
  DB_ROOT_PASSWORD: "rootpassword123"
  KEYCLOAK_ADMIN_PASSWORD: "admin123"
  SMTP_USER: "2b60af7702fbe7282ba786462af592f7"
  SMTP_PASS: "bb7dcf57a95e97cd349e111a9da5add5"
